name: hello
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^0.3.8
  provider: ^4.0.3
  contacts_service: ^0.3.10
  firebase_core: ^0.4.3+3
  firebase_auth: ^0.14.0+5
  cupertino_icons: ^0.1.2
  google_sign_in: ^4.1.1
  font_awesome_flutter: ^8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
